config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'developers#index'

  resources :users, only: [:show]
  resources :developers, only: [:show, :index, :new, :create] do
    resource :projects, only: [:new, :create]
    
    # post '/projects' => 'projects#create'
    # get '/projects/new' => 'projects#new'
  end
  
  resources :languages, only: [:show, :index]

  resources :projects, only: [:index] do
    member do
      put "upvote", to: "projects#upvote"
      put "unvote", to: "projects#unvote"
    end
  end
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_many :projects

  validates :first_name, presence: true
  validates :last_name, presence: true
  
  def full_name
  "#{first_name} #{last_name}"
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :participations, dependent: :destroy
  has_and_belongs_to_many :projects, :join_table => "participation"
  
  
  
  #validates :title, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :developer
  has_many :participation, dependent: :destroy
  has_and_belongs_to_many :languages, :join_table => "participation"
  acts_as_votable

  validates :developer, presence: true
  validates :name, presence: true#, uniqueness: true
  validates_uniqueness_of :name, scope: :developer #added validation of the uniuniqueness of name but only for a particular developer
  validates :description, presence: true
  
  accepts_nested_attributes_for :languages #iza
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 6..128
end
# added password_length: 6..128 to make one test pass

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :authenticate_user!

  def show
    @developer = Developer.find(params[:id])
  end

  def index
    @developers = Developer.all
  end

  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)

    if @developer.save
      flash[:success] = 'Developer saved'
      redirect_to developers_path
    else
      flash[:danger] = 'Developer could not be saved'
      render :new
    end
  end

  private

  def developer_params
    params.require(:developer).permit(:first_name, :last_name)
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_user!
  #before_action :find_projects
 
  def show
    #@project = Project.find(params[:id])
    #@language = @project.languages.build
    #@project = Project.find(params[:project_id])
    @language = Language.find(params[:id])
  end
  
   
  def index
    @languages = Language.all
  end
  
  
  private

  def language_params
    params.require(:language).permit(:name)
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :upvote, only: [:upvote, :unvote], except: :index

  def index
    @projects = Project.all
  end

  def new
    @developer = Developer.find(params[:developer_id])
    @project = @developer.projects.build
  end

  def create
    @developer = Developer.find(params[:developer_id])
    @project = @developer.projects.build(project_params)

    if @project.save
      flash[:success] = 'Project saved'
      redirect_to projects_path
    else
      flash[:danger] = 'Project could not be saved'
      render :new
    end
  end
  
  def upvote
    #@developer = Developer.find(params[:developer_id])
    #@project = @developer.projects.build(project_params)
    @project = Project.find(params[:id])
    @project.like_by current_user
    redirect_to :back
  end
  
  def unvote
    #@developer = Developer.find(params[:developer_id])
    @project = Project.find(params[:id])
    @project.dislike_by current_user
    redirect_to :back
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/developers/index.html.haml
%h1 Developers

.section
  = link_to 'Add developer', new_developer_path
  %br/

%h2 All developers
- @developers.each do |developer|
  .developer
    = link_to developer.full_name, developer_path(developer)
    %br/
    Project count:
    = developer.projects.count
    %br/
    Joined at:
    = developer.created_at.strftime("%d/%m/%Y")

app/views/developers/new.html.haml
%h1 New developer

= simple_form_for @developer do |f|
  = f.input :first_name
  = f.input :last_name
  = f.submit :save

app/views/developers/show.html.haml
%h1= @developer.full_name

.projects
  %h2 Projects
  = render @developer.projects
  
  .section
    = link_to 'Add project', new_developer_projects_path(:developer_id => @developer.id)
    %br/

app/views/languages/index.html.haml
%h1 All languages

- @languages.each do |language|
    = link_to language.name, language_path(language.id)
    %br/

app/views/languages/show.html.haml
%h1=@language.name

.projects
  %h2 Projects
  - @language.projects.each do |project|
    =project.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RecruitmentTask
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %span Rectruitment Task
      = link_to t('Logout'), destroy_user_session_path, method: :delete
      %ul
        %li= link_to 'Developers', developers_path
        %li= link_to 'Projects', projects_path
        %li= link_to 'Languages', languages_path
        - flash.each do |type, message|
          = message

    = yield

app/views/projects/_project.html.haml
.project
  Developer:
  = project.developer.full_name
  %br/
  Name:
  = project.name
  %br/
  Description
  = project.description
  %br/
  = link_to "Vote", upvote_project_path(project), method: :put
  %br/
  = link_to "Unvote", unvote_project_path(project), method: :put
  %br/
  Votes:
  = project.votes_for.size

app/views/projects/index.html.haml
%h1 All projects

= render @projects

app/views/projects/new.html.haml
%h1 New project

= simple_form_for [@developer, @project] do |f|
  = f.input :name
  = f.input :description
  = f.association :languages, label_method: :name, value_method: :id, label: 'Languages', as: :check_boxes
  = f.submit :save

app/views/users/show.html.haml
%h1= @user.email